local T = picocalc.sys.loadlib("picotest")

T.case("resume_yield_values", function()
    local co = coroutine.create(function(a, b)
        local c = coroutine.yield(a + b)
        return c * 2
    end)
    local ok, v = coroutine.resume(co, 1, 2)
    T.eq(ok, true); T.eq(v, 3)
    ok, v = coroutine.resume(co, 5)
    T.eq(ok, true); T.eq(v, 10)
    T.eq(coroutine.status(co), "dead")
    ok, v = coroutine.resume(co)
    T.eq(ok, false); T.ok(tostring(v):find("dead"), tostring(v))
end)

T.case("nested_running_and_isyieldable", function()
    local main = coroutine.running()
    local inner = coroutine.create(function()
        return coroutine.running(), coroutine.isyieldable()
    end)
    local outer = coroutine.wrap(function()
        local ok, who, y = coroutine.resume(inner)
        return ok, who, y, (coroutine.running())
    end)
    local ok, who, y, outer_self = outer()
    T.eq(ok, true); T.eq(who, inner); T.eq(y, true)
    T.ok(outer_self ~= main)
    T.eq(select(2, coroutine.running()), true)
end)

T.case("close_runs_tbc_handlers", function()
    local log = {}
    local co = coroutine.create(function()
        local x <close> = setmetatable({}, { __close = function() log[#log + 1] = "closed" end })
        coroutine.yield()
    end)
    coroutine.resume(co)
    T.eq(coroutine.close(co), true)
    T.eq(log[1], "closed")
    T.eq(coroutine.status(co), "dead")
end)

T.case("close_reports_handler_error", function()
    local co = coroutine.create(function()
        local x <close> = setmetatable({}, { __close = function() error("boom") end })
        coroutine.yield()
    end)
    coroutine.resume(co)
    local ok, err = coroutine.close(co)
    T.eq(ok, false); T.ok(tostring(err):find("boom"), tostring(err))
end)

T.case("wrap_error_closes_coroutine", function()
    local closed = false
    local f = coroutine.wrap(function()
        local x <close> = setmetatable({}, { __close = function() closed = true end })
        error("fail")
    end)
    local ok, err = pcall(f)
    T.eq(ok, false); T.ok(tostring(err):find("fail"), tostring(err))
    T.eq(closed, true)
end)

T.case("cannot_close_running", function()
    local co
    co = coroutine.create(function() return coroutine.close(co) end)
    local ok, err = coroutine.resume(co)
    T.eq(ok, false)
    T.ok(tostring(err):find("cannot close a running coroutine"), tostring(err))
end)

T.done()
