# pico_time's default alarm pool — a fixed copy of the SDK's time.c (issue #58).
#
# In SDK 2.2.0 (what release builds pin), alarm_pool_irq_handler's
# cancellation pass moves each cancelled entry to the front of the ordered
# list through `prev`, the link that points at it. When the head itself is
# cancelled it stays where it is, but `prev` is left pointing at
# pool->ordered_head instead of the head's own `next`, so the next cancelled
# entry in the same pass is unlinked by overwriting ordered_head: the old head
# drops out of every list and its pool slot is gone until a reboot. Any two
# alarms at the front of the list cancelled before the handler runs do it
# (the CYW43 driver's cross-core wake-ups cancel all the time, and other
# cancels pair with them). On the device the pool lost a few of its 16 slots
# per video session with WiFi on; once it was full the keyboard bus engine
# could not arm its timeout (it has its own hardware alarm now), the USB
# console's one-shot alarms failed so dev-command transfers crawled and
# aborted, and (by reading; not seen) the CYW43 driver's async context, which
# retries its alarm in a loop, would spin in its low-priority interrupt.
# SDK 2.3.1 rewrote
# that pass (raspberrypi/pico-sdk#3127): the fix below is the one line it
# needs, `prev` stepping past a head that stays.
#
# picodeck_patch_pico_time() compiles a copy of the SDK's time.c with that
# line added (written under CMAKE_BINARY_DIR/sdk_patched; the SDK is never
# modified) in place of the original, when the original still has the 2.2.0
# pass. Any other SDK builds unpatched, with a status message: drop this file
# once the SDK is bumped past 2.3.0. Call it after pico_sdk_init().

function(picodeck_patch_pico_time)
    if(NOT TARGET pico_time)
        message(FATAL_ERROR "picodeck_patch_pico_time: no pico_time target; "
                            "call it after pico_sdk_init()")
    endif()
    get_target_property(_srcs pico_time INTERFACE_SOURCES)
    set(_src "")
    foreach(_s IN LISTS _srcs)
        if(_s MATCHES "/pico_time/time\\.c$")
            set(_src "${_s}")
        endif()
    endforeach()
    if(NOT _src OR NOT EXISTS "${_src}")
        message(FATAL_ERROR "picodeck_patch_pico_time: pico_time has no time.c "
                            "(${_srcs}); update cmake/picodeck_pico_time.cmake")
    endif()
    file(READ "${_src}" _text)
    set(_from
"                        pool->ordered_head = index;
                    }
                } else {
                    prev = &entry->next;")
    set(_to
"                        pool->ordered_head = index;
                    } else {
                        // PicoDeck (cmake/picodeck_pico_time.cmake): a head
                        // that stays put is passed like any other entry, or
                        // the next cancelled one overwrites ordered_head and
                        // the head leaks out of every list.
                        prev = &entry->next;
                    }
                } else {
                    prev = &entry->next;")
    string(FIND "${_text}" "${_from}" _at)
    if(_at EQUAL -1)
        message(STATUS "picodeck_patch_pico_time: ${_src} does not have SDK "
                       "2.2.0's cancellation pass; building it unpatched")
        return()
    endif()
    string(REPLACE "${_from}" "${_to}" _text "${_text}")
    set(_text "/* PicoDeck: patched copy of ${_src}\n   generated by cmake/picodeck_pico_time.cmake (issue #58) — do not edit. */\n${_text}")
    set(_dst "${CMAKE_BINARY_DIR}/sdk_patched/pico_time/time.c")
    # Only rewrite when the content changes, so rebuilds stay incremental.
    set(_write TRUE)
    if(EXISTS "${_dst}")
        file(READ "${_dst}" _old)
        if("${_old}" STREQUAL "${_text}")
            set(_write FALSE)
        endif()
    endif()
    if(_write)
        file(WRITE "${_dst}" "${_text}")
    endif()
    list(REMOVE_ITEM _srcs "${_src}")
    list(APPEND _srcs "${_dst}")
    set_property(TARGET pico_time PROPERTY INTERFACE_SOURCES "${_srcs}")
    # Re-run the patch when the SDK's file changes.
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_src}")
    message(STATUS "picodeck_patch_pico_time: alarm pool cancellation fix applied")
endfunction()
